AkunaApp/urls.py
from django.urls import path
from .views import HomeView,CartDetailView,AnnonymousPanierJsonView,ProduitDetailView

urlpatterns = [
    path('',HomeView.as_view(),name='Akuna-Accueil'),
    path('update_commande/',AnnonymousPanierJsonView.as_view(),name='detail_commande'),
    path('create_cart/',AnnonymousPanierJsonView.as_view(),name='create_cart'),
    path('panier/',CartDetailView.as_view(),name='cart'),
    path('add-Cart-Item/',AnnonymousPanierJsonView.as_view(),name='add_cart_item'),
    path('update_cart/',AnnonymousPanierJsonView.as_view(),name='update_cart'),
    path('<int:pk>/<slug:slug>/',ProduitDetailView.as_view(),name='detail-produit'),
]

AkunaShop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

from . import settings

urlpatterns = [
    path('',include('AkunaApp.urls')),
    path('admin/', admin.site.urls),
]

#En absence de django.contrib.staticfiles et en mode DEBUG
if( settings.DEBUG == True and 'django.contrib.staticfiles' not in settings.INSTALLED_APPS):
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

if( settings.DEBUG == True):
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

AkunaApp/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User,AnonymousUser


import datetime

class Categorie(models.Model):
    """
        La classe modèle pour les catégories. 
    """
    libelle = models.CharField(_("Libelle"), max_length=150) 
    description = models.TextField(_("Description"), max_length="500", null=True,blank=True)
    create_date =  models.DateTimeField(_('Date de création'),auto_now_add=True)
    modified_date = models.DateTimeField(_("Date demodification"),auto_now=True)

    class Meta:
        managed = True
        verbose_name = 'categorie'
        verbose_name_plural = 'categories'

    def __str__(self):
        return (self.libelle)
    
    # def get_absolute_url(self):
    #     return reverse("model_detail", kwargs={"pk": self.pk})
    


class Produit(models.Model):
    """ 
        La classe modèle produit pour les produits.
    """
    categorie = models.ForeignKey(Categorie,on_delete=models.CASCADE)
    libelle =  models.CharField(_("Libelle"),max_length=500)
    image = models.ImageField(_("Illustration"),upload_to='akuna_produits')
    description = models.TextField(_("Description"))
    slug=models.SlugField(_('slug'))
    prix_unitaire = models.FloatField(_("Prix Unitaire"))
    quantite_stock = models.IntegerField(_("Quantite en stock"))    
    create_date = models.DateTimeField(_("Date de création"), auto_now_add=True)
    modified_date = models.DateTimeField(_('Date de modification'), auto_now=True)
    
    # delete_date = models.DateField(_("Date de suppresion"), auto_now=True)
    class Meta:
        managed = True
        verbose_name = 'produit'
        verbose_name_plural = 'produits'

    def __str__(self):
        return self.libelle
    
    def get_absolute_url(self):
        from django.urls import reverse
        return reverse("detail-produit", kwargs={"pk":self.id,"slug": self.slug})

class Client(User):
    """
        Class modèle pour les clients.
    """

    entreprise =  models.CharField(_("Entreprise"), max_length=500)
    commune = models.CharField(_("Commune"), max_length=500)
    quartier  = models.CharField(_("Quartier"), max_length=500)

    class Meta:
        verbose_name = 'client'
        verbose_name_plural = 'clients'
        

    def __str__(self):
        return ("{0} {1}".format(self.username))

class Profile(models.Model):
    """
        Classe modèle pour attribuer un profile client à chaque client.
    """
    
    client =  models.OneToOneField(Client,on_delete=models.CASCADE)
    avatar = models.ImageField(_("Photo de profile"),upload_to = "clients_avatar")
    create_date = models.DateTimeField(_("Date de création"), auto_now_add=True)
    modified_date = models.DateTimeField(_('Date de modification'), auto_now=True)
    

    class Meta:
        managed = True
        verbose_name = 'client_profile'
        verbose_name_plural = 'client_profiles'

class Commande(models.Model):
    """
        Classse modèle pour les commandes.
    """
    date = models.DateTimeField(_('Date'))
    etat  = models.BooleanField(_("Etat"))
    info_livraison = models.TextField(_("Informations de livraison"))
    total = models.IntegerField(_("Total"))

    class Meta:
        
        verbose_name = 'commande'
        verbose_name_plural = 'commandes'

    def __str__(self):
        return self.name
        

class PanierModel(models.Model):
    """
    Le modèle de panier
    """
    create_date = models.DateTimeField(_("Date de création"), auto_now_add=True)
    modified_date = models.DateTimeField(_('Date de modification'), auto_now=True)

    class Meta:
        db_table = ''
        managed = True
        verbose_name = 'PanierModel'
        verbose_name_plural = 'PanierModels'
    
    def __str__(self):
        
        return (str(self.id))

class PanierElementModel(models.Model):
    """
    Le modèle du contenu du panier
    """
    panier = models.ForeignKey(PanierModel,on_delete=models.CASCADE)
    produit = models.ForeignKey(Produit,on_delete=models.DO_NOTHING)
    quantite = models.IntegerField(_("Quantite"),default=1)
    date_ajout = models.DateTimeField(_("Date d'ajout"),auto_now_add=True)
    date_modif = models.DateTimeField(_("Date modification"),auto_now=True)

    class Meta:
        db_table = ''
        ordering = ['date_ajout']
        managed = True
        verbose_name = 'PanierElementModel'
        verbose_name_plural = 'PanierElementModels'
        
    def __str__(self):
        return(str(self.id))

    
    def total(self):
        """
        docstring
        """
        return(self.quantite*self.produit.prix_unitaire)

    def libelle(self):
        return(self.produit.libelle)
    
    def prix_unitaire(self):
        return(self.produit.prix_unitaire)

    def augment_quantite(self,quantite):
        self.quantite += int(quantite)
        self.save()

    def reduire_quantite(self,quantite):
        self.quantite -= quantite
        self.save()

    def get_absolute_url(self):
        return(self.produit.get_absolute_url())

    def delete(self, using=None, keep_parents=False):
        return super().delete(using=using, keep_parents=keep_parents)
    

class DetailCommande(models.Model):
    """
        La classe modèle pour la liste de produits.
    """
    produit = models.ForeignKey(Produit,on_delete=models.CASCADE)
    pu_prod = models.IntegerField(_('PU'),help_text="Prix Unitaire du produit.")
    commande = models.ForeignKey(Commande,on_delete=models.CASCADE)
    quantite = models.IntegerField(_("Quantité"),default=1)
    create_date = models.DateTimeField(_("Date"), auto_now_add=True,help_text="Date de création")
    modified_date = models.DateTimeField(_('Date de modification'), auto_now=True)
    
    class Meta:
        
        verbose_name = 'liste'
        verbose_name_plural = 'listes'

AkunaApp/forms.py
from django import forms

class RechercheForm(forms.Form):
    """
    le formulaire de recherche
    """
    pass

class ajoutAuPanier(forms.Form):
    pass

AkunaApp/views.py
from django.views.generic.list import ListView
from django.views.generic import DetailView,TemplateView,View
from django.contrib.auth.models import User
from django.shortcuts import render
from django.http import JsonResponse,HttpResponse
from django.core.exceptions import ValidationError,ObjectDoesNotExist
from django.shortcuts import Http404

from .models import Produit,Categorie,PanierModel,PanierElementModel
import json

class HomeView(ListView):
    
    ctx={}
    model = Produit
    template_name='AkunaApp/index.html'

    def get_context_data(self,**kwargs):
        
        self.ctx= super(HomeView,self).get_context_data(**kwargs)
        try:
            categories = Categorie.objects.all()
        except ObjectDoesNotExist as e:
            return(Http404())
        self.ctx["categories"]=categories
        return(self.ctx)
        
    def get_queryset(self):
        return super().get_queryset()

    def get_template_names(self):
        return super().get_template_names()
    

class ProduitDetailView(DetailView):
    model = Produit
    template_name ='AkunaApp/detail.html'
    # queryset = PanierElementModel.obejects.all()

class CartDetailView(ListView):
    template_name = "AkunaApp/cart.html"
    model = PanierElementModel
    def get_context_data(self, **kwargs):
        context = super(CartDetailView,self).get_context_data(**kwargs)
        if(self.request.user.is_authenticated):
            pass
        else:
            cookie_cart = json.loads(self.request.COOKIES['cart'])
        try:
            cart = PanierModel.objects.get(pk=int(cookie_cart['id']))
        except ObjectDoesNotExist as e:
            print(e)
        self.queryset = self.get_queryset().filter(panier=cart)
        context['panier_elts'] = self.get_queryset()
        return(context)
    
    def delete(self,*args, **kwargs):
        pass
    
    def get_queryset(self):
        return super().get_queryset()
    
    

class AnnonymousPanierJsonView(View):

    def get(self,*args,**wargs):
        if(self.request.is_ajax()):
            if(self.request.GET.get('action')=='create_cart'):
                cart = PanierModel()
                cart.save() #Ecrire un signal qui va surveillé cet objet pour qu'il soit suprimé apres 2 semaines
                return(JsonResponse(cart.id,safe=False))
        return(JsonResponse(None,safe=False))

    
    def post(self,*args,**kwargs):
        if(self.request.is_ajax()):
            action = self.request.POST.get('action')
            cart_id = self.request.POST.get('cart')
            if(action=="add_Item"):
                cart_id = int(cart_id)
                cart = PanierModel.objects.get(pk=cart_id)
                product_id = self.request.POST.get('produit')
                product_id = int(product_id)
                produit = Produit.objects.get(pk=product_id)
                cart_item = PanierElementModel(panier=cart,produit=produit)
                cart_item.save()
                return(JsonResponse(cart_item.produit.id,safe=False))
            elif(action == "del_Item"):
                pass
            elif(action == "del_all"):
                pass
            else:
                pass

            
        else:
            print(self.request.POST)

    def put(self,*args,**kwargs):
        """
        La méthode de modification d'une détail la commande
        """
        if(self.request.is_ajax()):
            # action = self.request.PUT.get('action')
            # cart_id = self.request.PUT.get('cart')
            # new_value = self.request.PUT.get('new_value')
           
            print(type(self.request.body))

    def delete(self,data,args):
        """
        La méthode de suppression de contenu du panier.
        """
        pass

AkunaApp/templates/AkunaApp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="Fr-fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href=" {% static 'akunaApp/css/style.css' %}" media="all" >
    <link rel="stylesheet" href=" {% static 'akunaApp/css/owl/owl.carousel.min.css' %}" media="all" >
    <link rel="stylesheet" href=" {% static 'akunaApp/css/owl/owl.theme.default.min.css' %}" media="all" >
    <title>
        {% block title %}
          
        {% endblock title %}      
    </title>
    {% block addHead %}
      
    {% endblock addHead %}
</head>
<body>
    {% block content %}
      
    {% endblock content %}
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js" type="text/javascript"></script>
    {% comment %} <script src=" {% static 'AkunaApp/js/JQuery.js' %} "></script> {% endcomment %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/559f62c62a.js" crossorigin="anonymous"></script>  
    <script  type="text/javascript" src="{% static 'AkunaApp/js/owl/owl.carousel.min.js' %}" ></script>
    <script  type="text/javascript" src="{% static 'AkunaApp/js/main.js' %}?20181209" ></script>
    <script  type="text/javascript" src="{% static 'AkunaApp/js/cookies.js' %}?20181209" ></script>
    <script  src="{% static 'AkunaApp/js/cart.js' %}?20181209"></script>
    {% block addScript %}
    {% endblock addScript %}
</body>
</html>

AkunaApp/templates/AkunaApp/cart.html
{% extends 'AkunaApp/index.html' %}
{% block main-content %}
<div class="row d-flex justify-content-center align-items-center mt-5  ">
	<hr class="w-25" />
	<h2 class="" >Mon<strong class="panier">Panier</strong></h2>
	<hr class="w-25" />
</div>
<div class="row">
	<div class="col-md-8 col-xs-12">
		<form action="{% url 'cart' %}" method="post">
			{% csrf_token %}
				<table class="d-table justify-content-center shadow align-items-center table table-responsive mt-5" cellspacing="3">
						<thead>
							<tr class="mb-2 panier-titre rounded-top">
								<th class="product-remove" scope="col" ><i class="fa fa-shopping-cart"></th>
								<th class="product-thumbnail" scope="col">&nbsp;</th>
								<th class="product-name" scope="col">Produit</th>
								<th class="product-price" scope="col">Prix Unitaire</th>
								<th class="product-quantity" scope="col">Quantité</th>
								<th class="product-subtotal" scope="col">Sous-total</th>
							</tr>
						</thead>
						
						<tbody>
							{% for elt_panier in panier_elts %}
							<tr class="d-table-row mt-2" id="{{ elt_panier.id }}">
								<td class="d-flex  justify-content-center align-items-center">
									<div class="mt-3">
										<a href="#" class="delete_item d-flex justify-content-center align-items-center m-0" aria-label="suprimer-element" data-title="{{ elt_panier.produit.libelle }}" data-action="delete" data-cart_item="{{ elt_panier.id}}">
											<input type="hidden" name="{{ elt_panier.id }}" value="">
											<span class="mr-2 suprimer-produit-panier">Suprimer</span>
											<i class="fa fa-trash suprimer-produit-panier-icon"></i>
										</a>
									</div>
								</td>
								<td class="thumbnail">
									<a href="{{ elt_panier.produit.get_absolute_url }}">
										<img width="60" height="60" src="{{ elt_panier.produit.image.url }}" class=" border-0 img-thumbnail" alt="" loading="lazy" srcset="" sizes="(max-width: 500px) 100vw, 500px">
									</a>						
								</td>
								<td class="product-name" data-title="Produit">
									<div class="mt-3">
										<a href="{{ elt_panier.produit.get_absolute_url }}">{{ elt_panier.produit.libelle }}</a>
									</div>						
								</td>
								<td class="product-price" data-title="Prix">
									<div class="mt-3">
										<span class=""><bdi>{{ elt_panier.produit.prix_unitaire|floatformat:2 }} <span class="">CFA</span></bdi></span>
									</div>						
								</td>
								<td class="" data-title="Quantité">
									<div class="mt-2">
										<div class="quantity buttons_added">
											<span class="plus kt-spin-button kt-icon-angle-up"></span>
											<input type="number" id="quantity" class=" form-control-range form-control" step="1" min="1" max="{{ elt_panier.produit.quantite_stock }}" name="{{elt_panier.id}}" value="1" title="Qté" size="4" placeholder="" inputmode="numeric">
											<span class="minus kt-spin-button kt-icon-angle-down"></span>
										</div>
									</div>
								</td>
								<td class="product-subtotal" data-title="Sous-total">
									<div class="panier-sous-total mt-3">
										<span class=""><strong>{{elt_panier.total}} CFA</strong></bdi></span>
									</div>
								</td>
							</tr>
							{% endfor %}
							<tr class=" d-table-row mt-3">
								<td colspan="4" class="actions">
									<button type="submit" class=" btn btn-success btn-mise-a-jour" name="update_cart" value="Mettre à jour le panier" aria-disabled="true">Mettre à jour le panier<i class="fas fa-sync-alt ml-1"></i></button>
								</td>
								<td>
									<span class="total-panier"><strong>Total :</strong></bdi></span>
								</td>
								<td>
									<span class=" total-panier-somme "><strong>1 000 000 CFA</strong></bdi></span>
								</td>
							</tr>
						</tbody>
						
				</table>
		</form>
	</div>
	<aside class="col-md-3 d-flex position-fixed-top border rounded">
		<div class="aside-valide-panier">
			<h5 class="Bilan-panier panier ">Bilan</h5>
		</div>
		<a href="#" class="valide-panier btn border align-self-end form-control">Valider Panier</a>
	</aside>
</div>
{% endblock main-content %}

AkunaApp/templates/AkunaApp/detail.html
<h1>Detail</h1>

AkunaApp/templates/AkunaApp/index.html
{% extends "AkunaApp/base.html" %}
{% block title %}
  Akuna-SHOP-Accueil
{% endblock title %}

{% block content %}
  <main>
    {% include "AkunaApp/akuna-fragments/AkunaApp-header.html" %}
    <section class="container">
      {% block main-content %}
        <div class="row mt-3 d-flex justify-content-between">
          <aside class="col-md-2 col-sm-12 pt-2 rounded border shadow categorie-aside">
            {% for categorie in categories %}
              <div class="d-flex p-0 mb-2 align-content-center rounded justify-content-start border categorie">
                <button class="btn w-100 text-left catedgorie-btn" >{{ categorie.libelle }} <div class="badge badge-danger  badge-pill w-25 h-25"></div> </button>
              </div>
            {% endfor %}
          </aside>
          <div id="owl-carousel" class="col-md-7 shadow rounded p-0 owl-theme owl-carousel">
            <div class="carousel-elt">
              <img class=" rounded " src=https://via.placeholder.com/720x450 height="400" alt="" srcset=""/>
            </div>
            <div class=" carousel-elt">
              <img class=" rounded " src=https://via.placeholder.com/720x450 height="400" alt="" srcset=""/>
            </div>
            <div class="carousel-elt">
              <img class=" rounded " src=https://via.placeholder.com/720x450 height="400" alt="" srcset=""/>
            </div>
            <div class=" carousel-elt">
              <img class=" rounded " src=https://via.placeholder.com/720x450 height="400" alt="" srcset=""/>
            </div>
          </div>
          <aside class="col-md-2 col-sm-12 pt-2 rounded border shadow categorie-aside">
            {% for categorie in categories %}
              <div class="d-flex p-0 mb-2 align-content-center rounded justify-content-start border categorie-aside-div">
                {% csrf_token %}
                <button class="btn bg-transparent w-100 text-left produit-btn" >{{ categorie.libelle }} <span class="badge badge-danger  badge-pill w-25 h-25"></span> </button>
              </div>
            {% endfor %}
          </aside>
        </div>
        <div class="row mt-3">
          <div class="container produits mt-2">
            <div class="row d-flex align-content-center justify-content-center mt-3 mb-3"><hr class="w-25 "><h5 class="text-muted">COMPOSANTS ELECTRONIQUES</h5> <hr class="w-25"> </div>
            <div class="row d-flex justify-content-between align-content-between mb-4 ">
              {% for produit in produit_list %}
                <div class="card shadow mb-2" style="width: 250px;">
                 <a href="{{produit.get_absolute_url}}"> <img  src="{{produit.image.url}}" alt="" class="img-thumbnail card-img-top"></a>
                  <div class="card-body">
                    <div class="d-flex align-content-center mb-2 justify-content-center">
                      <h5 class="card-title produit-name mr-auto"  >{{ produit.libelle|capfirst }}</h5>
                        <button class="add-cart-btn btn btn-outline-success border-0 rounded-pill update-cart" data-action="add"  data-produit={{ produit.id }}><i class="fa fa-cart-plus" aria-hidden="true"></i></button>
                      {% comment %} <form method="post" data-id:"{{produit.id}}" data-name:"{{produit.libelle}}" data-categorie:"{{produit.categorie}}" >
                        {% csrf_token %}
                      </form> {% endcomment %}
                      <a href="{{produit.get_absolute_url}}" class="btn border-0 btn-outline-success ml-1 rounded-pill"><i>Voir...</i></a>
                    </div>
                    <div class="card-footer border rounded">
                      <h4 class="produit-prix">
                        {{ produit.prix_unitaire|floatformat:2 }} CFA
                      </h4>
                    </div>
                  </div>
                </div>
              {% endfor %}
            </div>
          </div>
          <div class="akuna-produit-pagination">
            {% comment %} <span class="step-links">
              {% if page_obj.has_previous %}
                  <a href="?page=1">&laquo; first</a>
                  <a href="?page={{ page_obj.previous_page_number }}">previous</a>
              {% endif %}
      
              <span class="current">
                  Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
              </span>
      
              {% if page_obj.has_next %}
                  <a href="?page={{ page_obj.next_page_number }}">next</a>
                  <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
              {% endif %}
            </span> {% endcomment %}
          </div>
        </div>
        {% comment %} <div class="row catedorie-produit">
          <ul class="container nav nav-tabs nav-justified nav-link-ul" role="tablist">
            <li class="active nav-item">
              <a  data-toggle="tab" class="active" href="#Nouveau" class="link">NOUVEAUTES</a>
            </li>
            <li class="nav-item">
              <a  data-toggle="tab"  href="#Promo" class="link">PROMOTION</a>
            </li>
            <li class="nav-item">
              <a  data-toggle="tab" href="#En_vedette" class="link">VEDETTE</a>
            </li>
          </ul>
          <div class="tab-content">
            <div class="tab-pane fade active" id="Nouveau" >
              <div id="nouveau-carousel" class="active">
                <img src=https://via.placeholder.com/250x150  alt="" srcset=""/>
                <img src=https://via.placeholder.com/250x150  alt="" srcset=""/>
                <img src=https://via.placeholder.com/250x150  alt="" srcset=""/>
                <img src=https://via.placeholder.com/250x150  alt="" srcset=""/>
              </div>
            </div>
            <div class="tab-pane fade promo-carousel" id="Promo" >
              <div id="promo-carousel"> 
                <img src=https://via.placeholder.com/250x150 alt="" srcset=""/>    
                <img src=https://via.placeholder.com/250x150 alt="" srcset=""/>    
                <img src=https://via.placeholder.com/250x150  alt="" srcset=""/> 
                <img src=https://via.placeholder.com/250x150  alt="" srcset=""/> 
              </div>
            </div>
            <div class="tab-pane fade vedette-carousel" id="En_vedette" >
              <div id="vedette-carousel" class="d-flex vedette-carousel mt-2">
                <div class="card ">
                  <img class="card-img-top" src=https://via.placeholder.com/250x150 alt="" srcset=""/>    
                  <div class="card-body">
                    <h4 class="card-title">Libelle Produit</h4>
                    <p class="card-text">Prix </p>
                    <a href="#" class="card-link add-cart-btn">Ajouter au panier</a>
                  </div>  
                </div>  
                <div class="card">
                  <img class="card-img-top" src=https://via.placeholder.com/250x150 alt="" srcset=""/>    
                  <div class="card-body">
                    <h4 class="card-title">Libelle Produit</h4>
                    <p class="card-text">Prix </p>
                    <a href="#" class="card-link add-cart-btn">Ajouter au panier</a>
                  </div>  
                </div>  
                <div class="card">
                  <img class="card-img-top" src=https://via.placeholder.com/250x150 alt="" srcset=""/>    
                  <div class="card-body">
                    <h4 class="card-title">Libelle Produit</h4>
                    <p class="card-text">Prix </p>
                    <a href="#" class="card-link add-cart-btn">Ajouter au panier</a>
                  </div>  
                </div>  
                <div class="card">
                  <img class="card-img-top" src=https://via.placeholder.com/250x150 alt="" srcset=""/>    
                  <div class="card-body">
                    <h4 class="card-title">Libelle Produit</h4>
                    <p class="card-text">Prix </p>
                    <a href="#" class="card-link add-cart-btn">Ajouter au panier</a>
                  </div>  
                </div>  
              </div>
            </div>
          </div>
        </div> {% endcomment %}
      {% endblock main-content %}
    </section>
    <footer class="akunaApp-footer">
      <section class="akuna-informations"></section>
      <section class="copyright text-center">copyright-kkwaxy-2020</section>
    </footer>
  </main>
{% endblock content %}
  
{% block addScript %}
  <script type="text/javascript" >
    let user = '{{request.user}}';
  </script>
  {% load static %}

{% endblock addScript %}